name: Testing Buffy

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Testing and Building
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.3'

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)          

      - name: Testing
        run: |
          go test -v ./...

      # - name: Linting
      #   run: |
      #     curl -s  https://api.github.com/repos/dominikh/go-tools/releases/latest | jq -r '.assets[].browser_download_url' | grep "linux_amd64.tar.gz$" | wget -qi -

      - uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Report all results.
          filter_mode: nofilter
          # Exit with 1 when it find at least one finding.
          fail_on_error: false

      - name: Building app (linux)
        run: |
          go build main.go

